export const Data = [
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: '19 min away',
        ride_time: '10:34PM',
        cost: "$19.98",
        vehicle: "XL",
        rating: "5 stars",
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: '19 min away',
        ride_time: '10:34PM',
        cost: "$19.98",
        vehicle: "XL",
        rating: "5 stars",
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: '19 min away',
        ride_time: '10:34PM',
        cost: "$19.98",
        vehicle: "XL",
        rating: "5 stars",
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: '19 min away',
        ride_time: '10:34PM',
        cost: "$19.98",
        vehicle: "XL",
        rating: "5 stars",
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: '19 min away',
        ride_time: '10:34PM',
        cost: "$19.98",
        vehicle: "XL",
        rating: "5 stars",
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: '19 min away',
        ride_time: '10:34PM',
        cost: "$19.98",
        vehicle: "XL",
        rating: "5 stars",
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: '19 min away',
        ride_time: '10:34PM',
        cost: "$19.98",
        vehicle: "XL",
        rating: "5 stars",
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: '19 min away',
        ride_time: '10:34PM',
        cost: "$19.98",
        vehicle: "XL",
        rating: "5 stars",
        driver_name: 'Driver Name',
    },

  ];