export const rideData = [
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: 5,
        ride_time: 20,
        cost: 35.35,
        vehicle: "XL",
        rating: 5,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Lyft_logo.svg/1200px-Lyft_logo.svg.png',
        company: 'uber',
        eta: 6,
        ride_time: 19,
        cost: 19.98,
        vehicle: "XL",
        rating: 2,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: 7,
        ride_time: 18,
        cost: 16.70,
        vehicle: "XL",
        rating: 1,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Lyft_logo.svg/1200px-Lyft_logo.svg.png',
        company: 'uber',
        eta: 8,
        ride_time: 17,
        cost: 5.60,
        vehicle: "XL",
        rating: 4,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: 9,
        ride_time: 16,
        cost: 19.98,
        vehicle: "XL",
        rating: 4,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Lyft_logo.svg/1200px-Lyft_logo.svg.png',
        company: 'uber',
        eta: 10,
        ride_time: 15,
        cost: 19.98,
        vehicle: "XL",
        rating: 5,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: 11,
        ride_time: 14,
        cost: 13.00,
        vehicle: "XL",
        rating: 3,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Lyft_logo.svg/1200px-Lyft_logo.svg.png',
        company: 'uber',
        eta: 12,
        ride_time: 13,
        cost: 25.05,
        vehicle: "XL",
        rating: 4,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: 13,
        ride_time: 12,
        cost: 14.02,
        vehicle: "XL",
        rating: 5,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Lyft_logo.svg/1200px-Lyft_logo.svg.png',
        company: 'uber',
        eta: 14,
        ride_time: 11,
        cost: 16.02,
        vehicle: "XL",
        rating: 5,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: 15,
        ride_time: 10,
        cost: 20.11,
        vehicle: "XL",
        rating: 5,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Lyft_logo.svg/1200px-Lyft_logo.svg.png',
        company: 'uber',
        eta: 14,
        ride_time: 11,
        cost: 16.02,
        vehicle: "XL",
        rating: 5,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: 15,
        ride_time: 10,
        cost: 20.11,
        vehicle: "XL",
        rating: 5,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Lyft_logo.svg/1200px-Lyft_logo.svg.png',
        company: 'uber',
        eta: 14,
        ride_time: 11,
        cost: 16.02,
        vehicle: "XL",
        rating: 5,
        driver_name: 'Driver Name',
    },
    {
        company_logo: 'https://clipground.com/images/logo-uber-png-2.png',
        company: 'uber',
        eta: 15,
        ride_time: 10,
        cost: 20.11,
        vehicle: "XL",
        rating: 5,
        driver_name: 'Driver Name',
    },
  ];